[package]
name = "integration_tests"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bus_service_client = { path = "../bus_service_client"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
serial_test = "2.0.0"